version: 2

jobs:
  build:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
    steps:
      - checkout
      - run:
          command: |
            sudo apt -y install build-essential git
            git clone https://github.com/google/jsonnet.git
            cd jsonnet && make && make install
      - run:
          command: |
            go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
            go get github.com/brancz/gojsontoyaml      
      - run:
          command: |
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.10.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      - run:
          command: |
            ## only run 0.25.0 , not work after 0.25.0+
            ## because circleci machine run ubuntu 14
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.25.0/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
      - run:
          command: |
            sudo minikube start --vm-driver=none
      - run:
          command: |
            sudo minikube update-context
      - run:
          command: |
            JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until sudo kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
      - run:
          command: |
            sudo kubectl cluster-info
      - run:
          command: |
            sudo kubectl run circleci-example --image=nginx
      - run:
          command: |
            sudo kubectl get deployment